### ISSUE TITLE
Request: More didactic error message when invalid type in ambient.toml

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#1183]
Each time I have an invalid component type, I feel like there's a missed opportunity to teach me what the valid component types _are._

```toml
boid_neighbour_count = { type = "Usize" }
boid_neighbour_array = { type = "Array" }
```

```Error: Failed to resolve dependencies for pre-build

Caused by:
    Failed to resolve type `Usize` for component `boid_neighbour_count```

This error message could be followed with a message like the following:

```Valid types are `U8, U32, I8, I32, F32, Bool, EntityId, . . .````
