### ISSUE TITLE
Allow concepts to be used in queries

### ISSUE THREAD

**Issue by SK83RJOSH** [AmbientRun/Ambient#119]
```toml
[components]
aabb_min = { type = "Vec3", name = "AABB Min", description = "An AABB's min position."}
aabb_max = { type = "Vec3", name = "AABB Max", description = "An AABB's max position."}

[concepts.aabb]
name = "AABB"
description = "Arbitrarily Aligned Bounding Box."

[concepts.aabb.components]
"aabb_min" = {}
"aabb_max" = {}
```

Should generate:

```rust
pub fn aabb() -> (Component<f32>, Component<f32>) {
    (aabb_min(), aabb_max())
}
```

So that a user can:
```rust
// Query it
query(aabb()).build().bind(move |(min, max)| {});
// Require it
query(translation()).build().require(aabb()).bind(move |translation| {});
// Exclude it
query(translation()).build().exclude(aabb()).bind(move |translation| {});
// Blend it
query(translation()).build().blend(aabb()).bind(move |translation| {});
```
