### ISSUE TITLE
Structured events

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#228]
Right now events are just strings with an `Entity` as even data, but it would be nice to be able to have structured/typed events. Something like this in the `ambient.toml`:

```toml
[types]
DamageType = { enum = ["Fire", "Ice"] }

[events]
gun_fired = { damage = "u32", damage_type = "DamageType" }
```

Which could then be consumed like this:
```rust
on(gun_fired, |data| {
  println!("gun fired with {} damage", data.damage);
});
```
