### ISSUE TITLE
Support project dependencies with relative path

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#23]
Full dependency support is [a lot of work](https://medium.com/@sdboyer/so-you-want-to-write-a-package-manager-4ae9c17d9527). For now, we should support relative dependencies and see where that takes us:

```toml
[project]
id = "skinmesh"
name = "Skinmesh"
version = "0.0.1"

[dependencies]
peasant_man = { path = "../peasant_man" }
```

This should make `peasant_man`'s assets and components accessible to `skinmesh`. Additionally, if `peasant_man` introduces any scripts, they should be automatically added to the project, with an opt-out available (this may change if we develop support for spawning scripts from other scripts).
