### ISSUE TITLE
Implement RPCs with responses

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#253]
#240 allows for one-way messages, but we should support RPCs with responses:

```toml
[messages.hello]
name = "Hello"
description = "Sent when a client joins the server, then sent back from the server"
fields = { text = "String", source_reliable = "Bool" }
return = "String"
```

Implementor's side:
```rust
#[rpc(messages::Hello)]
fn hello(text: String, source_reliable: bool) -> String {
  format!("{text} {source_reliable}")
}
```

Guest side:
```rust
async fn main() {
  let response = messages::Hello::call(Target::NetworkReliable, "Hello world!", true).await;
  println!("{response}");
}
```
