### ISSUE TITLE
Consider using `toml` for asset pipeline

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#279]
Asset pipelines are described with a `pipeline.json`, but this seems a little inconsistent with the `ambient.toml`. We should consider using TOML instead, but we may need to redefine the structure to work around TOML's poor support for hierarchies.

**Comment by chaosprint** [comment]
Not sure if it's doable but it would be great if we can write everything in one `ambient.toml`.

**Comment by philpax** [comment]
I also considered that, but a benefit of the existing system is that you can have different pipelines for different levels of your folder hierarchy; not sure what the best way to express that with root-level settings would be.

**Comment by chaosprint** [comment]
> I also considered that, but a benefit of the existing system is that you can have different pipelines for different levels of your folder hierarchy; not sure what the best way to express that with root-level settings would be.

sth like this?

```toml
[pipeline1]
type = "Models"
collider = "FromModel"

[pipeline2]
type = "Audio"
```

**Comment by philpax** [comment]
Could do something like

```toml
[[pipeline]]
path = "assets/models"
type = "Models"
collider = "FromModel"

[[pipeline]]
path = "assets/audio"
type = "Audio"
```

Not sure if that would be better than keeping the pipelines near the assets they process... could see an argument for either approach.
