### ISSUE TITLE
Rough block out for Physics settings in Ambient.toml

### ISSUE THREAD

**Issue by SK83RJOSH** [AmbientRun/Ambient#281]
Since Ambient.toml and project macros are being refactored, now would be the perfect time to introduce a skeleton for physics layers/physics configuration.

We'd like something like this:
```toml
[physics]
collision_responses = [
  { layer_a = "player", layer_b = "projectile", filter = "Block" },
  { layer_a = "player", layer_b = "pickup", filter = "Overlap" },
  { layer_a = "pickup", layer_b = "projectile", filter = "Ignore" }
]

[physics.layers.player]
name = "Player"
description = "Layer for player collisions"

[physics.layers.projectile]
name = "Projectile"
description = "Layer for projectiles"

[physics.layers.pickup]
name = "Pick-Up"
description = "Layer for pick-ups"
```
