### ISSUE TITLE
Support loading a game with multiple heterogenous-located embers

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#678]
At present, the current implementation assumes that there is only one ember (e.g. `https://assets.ambient.run/some_ember_id`) or all embers are hosted in the same location (e.g. `http://localhost:8080/content/{built embers}`). However, we want to support embers from multiple locations:

```toml
[dependencies]
blah = { id = "iu42t84jgradas" }
blah2 = { id = "tihu345t3gsad" }
blah3 = { url = "https://cool.repository/my_cool_ember" }
```

At runtime, assets from `blah` should be found in `https://assets.ambient.run/iu42t84jgradas`, `blah2` from `https://assets.ambient.run/tihu345t3gsad` and `blah3` from `https://cool.repository/my_cool_ember`.

There is already some rudimentary support for this, but it needs to be expanded upon and made to work with the proxy, too. (i.e. the case where the embers are locally built and hosted by the server should continue to work)
