### ISSUE TITLE
Expose component defaults to manifest and API

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#698]
Following on from #697 - we should have a way to specify defaults for components that can be easily used in the API:

```toml
[components]
my_cool_component = { name = "My Cool Component", type = "U32", default = 42 }
```

```rust
Entity::new().with_default(my_cool_component())
// or
let def = my_cool_component().default(); // only available if defined in the schema
```

There's already a way to specify defaults within the host ECS, so it should hopefully be not too difficult to wire all of this up.
