### ISSUE TITLE
Macro produces incorrect code for enums in concepts

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#721]
When I wrote the code for the enum-in-concepts codegen, I made the assumption that enums would always be used as integers and that they'd be generated as constants. 

However, I figured out how to make *actual* enums work; unfortunately, the codegen has not been updated to handle this, so it still emits an integer in this case:

```toml
[enums.Silliness]
Little = ""
Lots = ""

[components]
silliness = { type = "Silliness" }

[concepts.concept_with_enum.components]
silliness = "Lots"
```

will generate `.with(silliness(), 1)` which will not compile.
