### ISSUE TITLE
Deployment IDs in pathed deps are bad

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#802]
See https://github.com/AmbientRun/Ambient/blob/main/guest/rust/packages/games/afps/mods/zombie/ambient.toml

Notice how `basic_character_animation` and `unit_schema` have the same deployment IDs; interestingly, it is not a valid deployment ID for _either_ package. Where is that ID coming from?
```toml
[dependencies]
afps_schema = { path = "../../schema", deployment = "4qcnuQpcxcMDogPdNsKl6s" }
basic_character_animation = { path = "../../../../std/basic_character_animation", deployment = "7GO4bqu6dZAbZqezzD4dbb" }
unit_schema = { path = "../../../../schemas/unit", deployment = "7GO4bqu6dZAbZqezzD4dbb" }
```

I expect that these deployment IDs are 'redundant' so packages with bad IDs like this will silently work until you take the code out of their local context.
