### ISSUE TITLE
Components aren't showing up in VSCode

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#908]
Repro:

1. `ambient new test`
2. Open in VSCode
3. Add this to `ambient.toml`:
```toml
[components]
testy = { type = "Duration" }
```
4. Go to main. Add this:
```rust
fn test_testy() {
    Entity::new().with(testy(), game_time()).spawn();
}
```
5. `testy` has red squiggly lines under it, but when I press `ctrl-.` it doesn't show "Import ..." to me, it only shows "Generate testy function"
