### ISSUE TITLE
Strange behaviour with package includes

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#916]
Reported by didey on Discord - a package with
```toml
[package]
id = "tlyvg31cph82qlpeheiqum2exwsn9sb4"
name = "wb"
version = "0.0.1"
content = { type = "Playable" }
ambient_version = "0.3.0-dev"

[includes]
player = "src/player/ambient.toml"
```

and
```toml
[package]
id = "player"
name = "player"
version = "0.0.1"
content = { type = "Asset", schema = true }
ambient_version = "0.3.0-nightly-2023-09-18"

[components.vertical_velocity]
type = "F32"
attributes = ["Debuggable", "Networked"]

[components.move_speed_modifier]
type = "F32"
attributes = ["Debuggable", "Networked"]
```

has strange effects with the Rust codegen. 

For them, the macro generates an error with an invalid reference to the `entity` function - presumably due to a relative import gone wrong generated by the macro.

For me, I get the much stranger behaviour of our WASM not loading at all. Disabling the include allows the WASM to load.

Looking at the state of the semantic with `cargo run -p ambient_package_semantic --example parse_manifest "project_path" > schema.txt`
 doesn't show anything amiss - the included scope is right where it should be - but it's tripping up something with the macro codegen.
